function Hd = fir_lp_window_blackman_harris(Fs,N,Fc)
%FIR_LP_WINDOW_BLACKMAN_HARRIS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.2 and the Signal Processing Toolbox 6.20.
% Generated on: 24-Jan-2016 16:11:42

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.

flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = blackmanharris(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
