function Hd = iir_bp_butterworth(Fs,N,Fc1,Fc2)
%IIR_BP_BUTTERWORTH Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.2 and the Signal Processing Toolbox 6.20.
% Generated on: 25-Jan-2016 13:35:00

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
